version: "3"
networks:
  mynet:
services:
  front:
    image: nginx:latest
    container_name: front
    volumes:
      - "./front/index.html:/usr/share/nginx/html/index.html"
      - "./front/javascript/delete.js:/usr/share/nginx/html/delete.js"
      - "./front/javascript/get.js:/usr/share/nginx/html/get.js"
      - "./front/javascript/post.js:/usr/share/nginx/html/post.js"
      - "./front/javascript/put.js:/usr/share/nginx/html/put.js"
    ports:
      - "5000:50"
    depends_on:
      - api
  db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-xe
    environment:
      ORACLE_USERNAME: system
      ORACLE_PASSWORD: oracle
    networks:
      - mynet
    ports:
      - "1521:1521"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: container-livros
    networks:
      - mynet
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@//oracle-xe:1521/XE
      SPRING_DATASOURCE_USERNAME: system
      SPRING_DATASOURCE_PASSWORD: oracle
    links:
      - db
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_started
