version: "3"
services:
  db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-xe
    networks:
      - mynet
    environment:
      ORACLE_USERNAME: system
      ORACLE_PASSWORD: oracle
    ports:
      - "1521:1521"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: container-livros
    restart: always
    depends_on:
      - db
    networks:
      - mynet
networks:
  mynet:
    driver: bridge